server {
    listen       80;
    server_name  _;

    root   /usr/share/nginx/html;
    index  index.html;

    # Tidak meng-cache index.html & data.js supaya update langsung terlihat
    location ~* \.(html|js)$ {
        add_header Cache-Control "no-cache, must-revalidate";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Sembunyikan versi nginx
    server_tokens off;
}
